# Generated by Django 3.1 on 2020-09-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0002_fuelnorm_fueltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelnorm',
            name='fuelTypeB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuelTypeB', to='specification.fueltype'),
        ),
        migrations.AlterField(
            model_name='fuelnorm',
            name='fuelType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelType', to='specification.fueltype'),
        ),
    ]
