# Generated by Django 3.1 on 2020-09-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0003_auto_20200901_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelnorm',
            name='fuelTypeC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fuelTypeC', to='specification.fueltype'),
        ),
    ]
