# Generated by Django 3.1 on 2020-09-01 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0006_auto_20200901_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='docDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
