# Generated by Django 3.1 on 2020-09-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0008_auto_20200901_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelnorm',
            options={'ordering': ['unit']},
        ),
    ]
